import { StyleSheet } from 'react-native';
import { space } from '@industry/tokens';

export const styles = StyleSheet.create({
  flex: { flex: 1 },
  container: {
    flex: 1,
    gap: space[4],
    paddingTop: space[4],
  },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  fab: { position: 'absolute', right: space[6] },
  trailingActions: { flexDirection: 'row', alignItems: 'center' },
  trailingIconButton: { padding: space[2] },
  trailingTextButton: { paddingHorizontal: space[3], paddingVertical: space[2] },
  trailingTextButtonLabel: { fontSize: 15, fontWeight: '600' },
  chartCard: {
    borderWidth: 1,
    padding: space[4],
    alignItems: 'center',
  },
  chartDonutWrapper: { position: 'relative', alignSelf: 'center' },
  chartTotal: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 140,
    alignItems: 'center',
    justifyContent: 'center',
  },
  chartTotalText: { fontSize: 19 },
  sectionLabelRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  sectionLabel: {
    fontSize: 11,
    letterSpacing: 1.1,
    textTransform: 'uppercase',
  },
  sectionLabelCount: { fontSize: 12 },
  sectionHairline: { height: 1, marginTop: space[2], marginBottom: space[3] },
  recentList: { gap: space[3] },
  recentItem: { gap: space[1] },
  recentHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: space[2],
  },
  recentTitle: { flex: 1, fontSize: 17, fontWeight: '600' },
  recentMeta: { fontSize: 12 },
  statCardWrapper: { marginLeft: space[2] },
  sectionPad: { paddingHorizontal: space[4] },
  listHeaderSpacer: { width: space[2] },
  listFooterSpacer: { width: space[4] },
  emptyState: { marginHorizontal: space[4] },
});
